export const colors = {
    bg: '#F4F9FF',
    bgWarm: '#FFF6FA',
    surface: '#FFFFFF',
    surfaceBlue: '#EAF4FF',
    surfacePink: '#FFF0F5',
    surfaceMuted: '#ECF4FC',
    border: '#D8E7F6',
    borderPink: '#F8C6D7',
    text: '#102333',
    muted: '#647789',
    soft: '#92A5B6',
    primary: '#5B9DE6',
    primaryDeep: '#2C78BD',
    primarySoft: '#DDEEFF',
    accent: '#F48EAD',
    accentDeep: '#D95F83',
    accentSoft: '#FFE2EC',
    success: '#2C78BD',
    successSoft: '#DDEEFF',
    warning: '#F48EAD',
    danger: '#D64A4A',
    dangerSoft: '#FBEAEA',
    ink: '#13283A',
    skeleton: '#E5EFF8',
    skeletonHighlight: '#F7FBFF',
};

export const shadow = {
    shadowColor: '#8BB6DE',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 3,
};
